import type { Metadata } from 'next'
import BlogPage from "@/views/Blog";

export const metadata: Metadata = {
  title: 'Blog yazıları',
  description: 'Generated by create next app',
}

export default function Blog() {
  return <BlogPage />
}
