import type { Metadata } from 'next'
import '@/style/global.scss'
import { Inter } from 'next/font/google'
import MainLayout from '@/layout/main'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tahsin Sungur - Frontend Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainLayout>
          {children}
        </MainLayout>
      </body>
    </html>
  )
}
