import type { Metadata } from 'next'
import MainLayout from '@/layout/MainLayout'
import '@/styles/globals.scss'

export const metadata: Metadata = {
  title: 'Tahsin Sungur',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* – Frontend Developer */}
      <body>
        <MainLayout>
          {children}
        </MainLayout>
      </body>
    </html>
  )
}
