import './globals.css';
import { Inter } from 'next/font/google';
import Header from '../components/header';
import Footer from '../components/footer';
import { fontVariables as geistVariables } from '../assets/fonts/geist';
import Shine from '../components/shine';
import Sidebar from '../components/sidebar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

const fontVariables = [...geistVariables.split(' '), inter.variable].join(' ');

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
        />
      </head>
      <body className={fontVariables}>
        {/* <Header /> */}
        {/* <Shine /> */}
        <section className="grid grid-cols-12 container gap-12 py-10">
          <Sidebar />
          <main className="flex flex-col gap-12 relative z-10 col-span-8">
            {children}
          </main>
        </section>
        <Footer />
      </body>
    </html>
  );
}
