import './globals.css';
import { Inter } from 'next/font/google';
import Header from '../components/header';
import Footer from '../components/footer';
import { fontVariables as geistVariables } from '../assets/fonts/geist';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

const fontVariables = [...geistVariables.split(' '), inter.variable].join(' ');

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
        />
      </head>
      <body className={fontVariables}>
        <Header />
        <div className="absolute w-full h-96 inset-0 top-0 z-[-9999] max-w-screen-sm bg-red-50 left-1/2 -translate-x-1/2 bg-gradient-to-br from-amber-600 via-zinc-950 to-zinc-950 blur-3xl opacity-30 pointer-events-none select-none" />
        <main className="container flex flex-col gap-12 my-10 relative z-10">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
